### ISSUE TITLE
Equation 6.106

### ISSUE THREAD

**Issue by jduerholt** [Allen-Tildesley/corrections#2]
Dear authors, 
from my point of view it seems like that equation 6.106 dealing with the surface term of a slab like sample is wrong. Instead of 2*pi*V*(qi*zi)**2 it should be 2*pi/V*(qi*zi)**2. Or am I wrong?
Best
Johannes Dürholt

**Comment by Michael-P-Allen** [comment]
Thanks for bringing this to our attention. I believe that you are correct, because our equation is not properly extensive, and also eqn (10) of Yeh and Berkowitz seems to be identical to your corrected version. I'll double check with my co-author, but assuming you are right, a correction will be added to the PDF document, with an acknowledgement.

**Comment by Michael-P-Allen** [comment]
We are agreed that this is an error. However, for unrelated reasons, it will be a couple of weeks before we upload the correction, and I'll delay closing this issue until then. Thanks again for spotting this.
Best regards
Mike
